### ISSUE TITLE
Have you tried to not connect the USB2.0 pins to the external port?

### ISSUE THREAD

**Issue by wzqvip** [LeoDJ/FW-EC-DongleHiderPlus#1]
Have you tried to make the external port "usb3 only" or add a switch next to the port, which can 'cut off' the usb2 pins.

The problem could be caused by the management of USB4, I did not find any case about this.

**Comment by LeoDJ** [comment]
Could be, that might work.
The best fix would be to just use a USB 3.0 hub IC, but I didn't want the added complexity, board space and cost.
Or just get rid of the USB 3 SS lanes altogether and define it as USB 2.0 only.

But honestly, for me personally, the compromise is absolutely fine as it is. My USB4 ports are pretty permanently occupied by USB-C expansion cards anyway, so I'll only use the DongleHider+ in the other slots.
(And even then I rarely use USB 3.0 devices with an A connectors)

But I can imagine some scenarios where the limitations would be more severe.
I also haven't tested on Intel FW13 yet (where all ports are USB4 iirc), maybe it won't work at all, who knows ^^"

I think I'll close this for now, as I don't plan to make another revision in the near future, but if anyone else wants to take a crack at it, feel free to fork / modify it to suit your needs ^^
