### ISSUE TITLE
Board Thickness - I believe it's incorrect

### ISSUE THREAD

**Issue by madeofpendletonwool** [LeoDJ/FW-EC-DongleHiderPlus#3]
Hi there,

Upon uploading the gerber file to JLCPCB the board thickness defaults to 1.6. I believe for the usb-c connector to work it would need to be 0.8 wouldn't it? Since the connector pins wraps around the board. Or is there someway to finagle the usb-c connector around the board that I'm not aware of?

Apologies if this isn't an actual issue? I certainly may just be understanding something incorrectly. 

Thanks!

**Comment by LeoDJ** [comment]
Yes, 0.8mm board thickness is correct, I've only documented the JLC settings in the release here: https://github.com/LeoDJ/FW-EC-DongleHiderPlus/releases/tag/v0.1

(afaik JLC always defaults to 1.6mm board thickness and doesn't read that information from the gerbers, in case it's even stored there)

**Comment by madeofpendletonwool** [comment]
Ahh I gotcha. My apologies, I should have spotted that. Thanks!
