### ISSUE TITLE
USB 3 on USB 2 hub

### ISSUE THREAD

**Issue by JirikP** [LeoDJ/FW-EC-DongleHiderPlus#7]
Hi, love your work, but the USB 3 will not work correctly like that. Quick fix is to just do USB 2 type A connector on the outside and remove the extra USB lines or try to find suitable USB 3 hub and re-do your board. This is not a correct way and can create unexpected behaviour ei. wont work as USB 3 line.

**Comment by LeoDJ** [comment]
Yes, this is known and quasi-intentional, see: https://github.com/LeoDJ/FW-EC-DongleHiderPlus?tab=readme-ov-file#compatibility-notes.

I didn't find a small enough USB 3 hub IC and wanted to try what would happen.

But feel free to improve the design for your requirements.
